DEV: Improved error handling
discourse/onebox pull request #437
Opened 2020-11-13 21:16 UTC by jbrw

- Expose hash of missing data elements. Can be used to construct error/warning messages if a onebox fails.

- Use new Instagram oEmbed endpoint, if an access token is provided.

2020-11-13 22:17 UTC, CvX requested changes
+ the commit/PR message should be updated to reflect all non error related changes 🙂

2020-11-13 22:17 UTC, CvX commented on lib/onebox/engine/instagram_onebox.rb
> +        if access_token && access_token != ''
```suggestion
        if access_token != ''
```

2020-11-13 22:17 UTC, CvX commented on lib/onebox/engine/instagram_onebox.rb
> +          description: oembed.title,
No truncation needed anymore?

2020-11-13 22:17 UTC, CvX commented on lib/onebox/engine/allowlisted_generic_onebox.rb
> +              errors[k] = 'is blank'
I think it was supposed to be:

```suggestion
              errors[k] ||= []
              errors[k] << 'is blank'
```

😉

2020-11-16 21:05 UTC, jbrw commented on lib/onebox/engine/allowlisted_generic_onebox.rb
> +              errors[k] = 'is blank'
Good catch!

2020-11-16 22:01 UTC, CvX approved these changes

2020-11-16 22:23 UTC, merged