FIX: Validate format of links
discourse/onebox pull request #447
Opened 2020-12-11 23:41 UTC by jbrw

Attempt to validate the format of URLs for image and video attributes, and remove any values that appear to be invalid.

2020-12-13 15:47 UTC, CvX requested changes

2020-12-13 15:47 UTC, CvX commented on lib/onebox/helpers.rb
> +      return "" unless parsed.host && parsed
```suggestion
      return "" unless parsed.host
```

Are there any cases where `parsed` could be falsy? Other than `url` being nil, but that won't happen in this case.

2020-12-13 15:47 UTC, CvX commented on lib/onebox/open_graph.rb
> +        Onebox::Helpers::blank?(result) ? nil : result
`::Onebox` or `Onebox`? 😃 

Also, maybe: `result unless Onebox::Helpers::blank?(result)`

2021-02-24 08:56 UTC, CvX commented
@jbrw ping 😃

2021-03-03 23:48 UTC, jbrw commented
> @jbrw ping 😃

Oh - this totally fell off my radar. Sorry about that.

I have made a note to self and will circle back to this tomorrow.

2021-03-04 21:46 UTC, CvX approved these changes

2021-03-04 21:54 UTC, merged